      MODULE FLAGS

!-      INTEGER HOURLYFLAG
      INTEGER RESUMEFLAG
      INTEGER SAVERESUMEFLAG 
      INTEGER SHDFILEFLAG
      INTEGER SOILINIFLAG
      INTEGER NRSOILAYEREADFLAG
!-      INTEGER CONFLAGS
      INTEGER RELFLG
!-      INTEGER OPTFLAGS
!-      INTEGER INTERPOLATIONFLAG
      INTEGER SUBBASINFLAG
      INTEGER R2COUTPUTFLAG
      INTEGER OBJFNFLAG
      INTEGER WINDOWSIZEFLAG
      INTEGER WINDOWSPACINGFLAG
      INTEGER METRICSSTATSOUTFLAG
      INTEGER METRICSFILTEROBSFLAG
      INTEGER METRICSSPINUP
      INTEGER METRICSINCLUDESPINUP
      INTEGER FROZENSOILINFILFLAG
!> JUN 03/11 - DGP      ADDED FOR WATDRN3
!> JUL 10/11 - DGP      WD3FLOW
!> AUG 19/11 - DGP      WD3BKFC
      INTEGER WD3
      INTEGER WD3NEWFILE
      INTEGER WD3FLOW
      INTEGER WD3BKFC
      INTEGER PBSMFLAG
!> JAN 30/14 - KCK     ADDED LOCATIONFLAG
      INTEGER LOCATIONFLAG

!> JUL 17/14 -GSA- GET FIELDS BALANCEs
      INTEGER OUTFIELDSFLAG

!> OCT 16/14 -GSA- GET Geothermal flux
      INTEGER GGEOFLAG
!> NOV 18/14 -GSA- Variable in/out file names
      INTEGER VARIABLEFILESFLAG

!-      INTEGER BASINBALANCEOUTFLAG
      integer :: BASINAVGEBFILEFLAG = 0
      integer :: BASINAVGEVPFILEFLAG = 0
      INTEGER MODELINFOOUTFLAG
      INTEGER :: BASINSWEOUTFLAG = 0

      END
